### ISSUE TITLE
Get no logs.

### ISSUE THREAD

**Issue by MalteKiefer** [inpsyde/logzio-monolog#12]
Hello,

I have this in my code:

```php
        $logger = new Logger($subdomain);
        $logger->pushHandler(new LogzIoHandler('TOKEN'));
```

This is my region:

```php
Region eu-west-2
```

But I get no logs? Did I'm missing something?

**Comment by Chrico** [comment]
Howdy Malte,

it seems, that the issue went lost in my inbox. Sry about that!

Can you give a bite more context where this is used and how? Any logs maybe? Is curl available on your system? Is it working with a different region?

Best greetings,
Chris

**Comment by OskarStark** [comment]
Maybe this helps? https://github.com/inpsyde/logzio-monolog/pull/14
