### ISSUE TITLE
Version 0.4 is locked to php 7

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/logzio-monolog#16]
As long as Wonolog is not compatible to Monolog 2 I have to use version 0.4 of this package. Unfortunately it's php version constraint excludes php 8:
```
"php": "^7.0",
```
I'd like to change that to `"php": ">=7.0" and test it and if it works with 8.1 we could create a 0.5 release.

**Comment by Chrico** [comment]
This has been fixed with version 0.4.1. 👍🏻
