### ISSUE TITLE
Implement support to ship logs to listener-eu

### ISSUE THREAD

**Issue by dgreda** [inpsyde/logzio-monolog#8]
Currently it is not possible to change the endpoint used by `LogzIoHandler` and so the library cannot be used to ship logs to `listener-eu` (https://docs.logz.io/user-guide/log-shipping/listener-ip-addresses.html).
I thought about either adding extra parameter into constructor or adding setter for the endpoint.

**Comment by Chrico** [comment]
merged and was released in 0.4. Just forgot to close the issue. :-)
